@extends('public.layout')

@section('title', app()->getLocale() === 'ar' ? 'عن NEXVARY وتقنيات الحماية' : 'About NEXVARY Security Technology')
@section('description', app()->getLocale() === 'ar' ? 'تعرف على NEXVARY ونهجها في الأمن السيبراني ومكافحة التجسس الفني والتحليل الجنائي الرقمي وتقنيات الخصوصية.' : 'Learn about NEXVARY and its approach to cybersecurity, counter-surveillance, digital forensics, privacy technology and layered protection.')
@section('canonical', 'https://nexvary.com/about')

@section('content')
@php($ar = app()->getLocale() === 'ar')
<main class="nx-section nx-page-body">
    <section class="nx-about-hero"><div><p class="nx-kicker">ABOUT NEXVARY</p><h1>{{ $ar ? 'تقنية أمنية مصممة لما لا يظهر للعين.' : 'Security technology for what is not immediately visible.' }}</h1><p class="nx-lead">{{ $ar ? 'تجمع NEXVARY بين الأمن السيبراني، مكافحة التجسس الفني، التحليل الجنائي الرقمي وتقنيات الخصوصية لبناء طبقات حماية مترابطة.' : 'NEXVARY combines cybersecurity, technical counter-surveillance, digital forensics and privacy technology into connected layers of protection.' }}</p></div><div class="nx-about-emblem" aria-hidden="true"><span>N</span></div></section>
    <div class="nx-grid nx-about-grid">@foreach([['Cybersecurity','Reducing attack surface and strengthening systems before incidents happen.'],['Counter-Surveillance','Technical inspection and awareness for environments where confidentiality matters.'],['Digital Forensics','Structured investigation and evidence handling with repeatable workflows.'],['Privacy Technology','Tools and architecture that minimize unnecessary data exposure by design.']] as $pillar)<article class="nx-card"><div class="nx-icon" aria-hidden="true">N</div><h2>{{ $pillar[0] }}</h2><p>{{ $pillar[1] }}</p></article>@endforeach</div>
    <div class="nx-ssr-copy" style="margin-top:34px">@if($ar)<p>تقوم فلسفة NEXVARY على أن الخطر لا يظهر دائمًا في صورة هجوم واضح. أحيانًا يكون الخطر في إعداد ضعيف، جهاز غير مؤمّن، تعرض غير ضروري للبيانات، بيئة حساسة لم تُفحص، أو دليل رقمي لم تتم المحافظة عليه بطريقة صحيحة. لذلك نربط بين الحماية الوقائية، الوعي الفني، الخصوصية، والتحقق الجنائي عند الحاجة.</p><p>لا نقدم كل إشارة تقنية باعتبارها حكمًا نهائيًا. الأدوات البرمجية تساعد على الكشف والفرز والتوثيق، بينما بعض الحالات تحتاج فحصًا متخصصًا أو معدات ميدانية أو إجراءات حفظ أدلة. هذا الفصل جزء أساسي من بناء منتج أمني موثوق، ويظهر أيضًا في طريقة عرض التطبيقات والمشاريع وحالة توفرها داخل الموقع.</p>@else<p>NEXVARY is built on the idea that security risk is not always visible as an obvious attack. Exposure may exist in a weak configuration, an unmanaged device, unnecessary data collection, an environment that has not been technically inspected, or digital evidence that was not preserved correctly. For that reason, the platform connects preventive protection, technical awareness, privacy engineering, and forensic validation when an incident requires evidence-based review.</p><p>Software signals are not presented as absolute conclusions. Defensive applications can help detect, classify, document, and prioritize issues, while some situations require specialist inspection, field equipment, or formal evidence-handling procedures. That distinction is part of the NEXVARY product model and is reflected in how services, applications, published projects, distribution status, and privacy expectations are communicated across the platform.</p>@endif</div>
    <section class="nx-contact-panel"><div><p class="nx-kicker">CONNECT</p><h2>{{ $ar ? 'روابط NEXVARY الرسمية' : 'Official NEXVARY channels' }}</h2></div><div class="nx-social-grid"><a href="https://nexvary.com/"><strong>Website</strong><small>nexvary.com</small></a><a href="https://www.facebook.com/share/14p9krEn5ij/" target="_blank" rel="noreferrer"><strong>Facebook</strong><small>Official page</small></a><a href="mailto:info@nexvary.com"><strong>Email</strong><small>info@nexvary.com</small></a><a href="https://www.youtube.com/@NexvaryInc" target="_blank" rel="noreferrer"><strong>YouTube</strong><small>@NexvaryInc</small></a><a href="https://x.com/Nexvary" target="_blank" rel="noreferrer"><strong>X</strong><small>@Nexvary</small></a></div></section>
</main>
@endsection
