@extends('public.layout')

@section('title', 'SafeScan Zero-Storage File Inspection')
@section('description', app()->getLocale() === 'ar' ? 'SafeScan يفحص خصائص الملفات محليًا داخل المتصفح دون رفع محتوى الملف إلى NEXVARY، مع خيار استخدام بصمة SHA-256 فقط.' : 'SafeScan performs primary browser-side inspection without uploading file contents to NEXVARY, with optional SHA-256 reputation lookup.')
@section('canonical', 'https://nexvary.com/safescan')

@section('content')
@php($ar = app()->getLocale() === 'ar')
<main>
    <section class="nx-hero nx-safescan-hero">
        <div class="nx-hero-copy"><p class="nx-kicker">ZERO-STORAGE · LOCAL-FIRST</p><div class="nx-product-heading"><div class="nx-icon" aria-hidden="true">S</div><h1>SafeScan</h1></div><p class="nx-lead">{{ $ar ? 'الفحص الأساسي يتم داخل المتصفح. لا يتم رفع محتوى الملف إلى خادم NEXVARY، ويمكن استخدام بصمة SHA-256 فقط للتحقق الاختياري من السمعة.' : 'Primary inspection runs in the browser. File contents are not uploaded to NEXVARY; only a SHA-256 hash may be used for an optional reputation lookup.' }}</p><div class="nx-trust-row"><span>Browser-side</span><span>SHA-256</span><span>No file retention</span><span>Privacy-first</span></div></div>
        <div class="nx-command"><div class="nx-radar"><span class="nx-sweep"></span><div class="nx-core">S</div></div><div class="nx-command-meta"><span><b>LOCAL</b>browser-side inspection</span><span><b>HASH</b>SHA-256 reputation option</span><span><b>PRIVATE</b>no file-content retention</span></div></div>
    </section>
    <section class="nx-section nx-scan-explainer"><div class="nx-section-title"><p>PRIVACY MODEL</p><h2>{{ $ar ? 'ما الذي يحدث لملفك؟' : 'What happens to your file?' }}</h2></div><div class="nx-grid"><article class="nx-card"><div class="nx-icon">01</div><h3>{{ $ar ? 'قراءة محلية' : 'Local read' }}</h3><p>{{ $ar ? 'يقرأ المتصفح خصائص الملف محليًا لإجراء التحليل الأساسي.' : 'The browser reads file characteristics locally for primary inspection.' }}</p></article><article class="nx-card"><div class="nx-icon">02</div><h3>SHA-256</h3><p>{{ $ar ? 'يمكن حساب بصمة تشفير للملف دون إرسال محتواه.' : 'A cryptographic fingerprint can be calculated without sending file contents.' }}</p></article><article class="nx-card"><div class="nx-icon">03</div><h3>{{ $ar ? 'تحقق اختياري' : 'Optional lookup' }}</h3><p>{{ $ar ? 'إذا تم تفعيل التحقق من السمعة، ترسل البصمة فقط إلى خدمة السمعة.' : 'If reputation lookup is enabled, only the hash is sent to the reputation service.' }}</p></article></div>
        <div class="nx-ssr-copy" style="margin-top:34px">@if($ar)<p>يعتمد SafeScan على مبدأ تقليل البيانات منذ البداية. بدلاً من رفع الملف الكامل إلى خادم مركزي لمجرد معرفة خصائصه الأساسية، يتم تنفيذ التحليل الأولي داخل المتصفح حيثما تسمح التقنية بذلك. هذا يقلل سطح التعرض ويمنح المستخدم فهمًا أوضح لما يغادر جهازه وما يبقى محليًا.</p><p>عند استخدام خيار السمعة، يمكن حساب بصمة SHA-256 للملف واستخدامها كمُعرّف تقني دون إرسال محتوى الملف نفسه. لا تعني نتيجة السمعة أن الملف آمن أو ضار بصورة قطعية؛ بل هي إشارة إضافية يجب تفسيرها مع سياق الملف ومصدره وسلوكه. الملفات الحساسة أو الحالات الجنائية تتطلب إجراءات أكثر تحفظًا وحفظًا للأدلة.</p>@else<p>SafeScan is built around data minimization. Instead of uploading a complete file simply to inspect basic characteristics, the primary analysis is performed in the browser wherever the platform permits. This reduces unnecessary exposure and gives the user a clearer understanding of what remains local and what may be shared with an external reputation service.</p><p>If reputation lookup is enabled, SafeScan can calculate a SHA-256 fingerprint and use that hash as a technical identifier without transmitting the original file contents. A reputation result is an additional signal, not a guarantee that a file is safe or malicious. Sensitive material, incident-response evidence, or forensic cases require stricter handling, preservation, and specialist validation beyond a browser-based preliminary inspection.</p>@endif</div>
    </section>
</main>
@endsection
