import { Head, useForm } from '@inertiajs/react';
import { FileText, Save } from 'lucide-react';
import { AdminNav } from '../../components/admin/admin-nav';
import { NxCard } from '../../components/ui/nx-card';

type Block = { key: string; locale: string; title: string | null; body: string | null; is_published: boolean };

export default function Content({ blocks }: { blocks: Block[] }) {
  const form = useForm({ key: 'home.hero', locale: 'en', title: '', body: '', is_published: false });
  return <><Head title="Content Management" /><main className="min-h-screen bg-slate-950 px-4 py-7 text-white sm:px-8"><div className="mx-auto max-w-7xl"><AdminNav active="Content" /><div className="mb-6 flex items-center gap-3"><FileText className="text-cyan-300"/><div><h1 className="text-3xl font-black">Content Management</h1><p className="text-sm text-slate-400">Database-backed multilingual content blocks.</p></div></div><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><NxCard><form onSubmit={(e) => { e.preventDefault(); form.post('/secure-control/content'); }} className="space-y-4"><label className="block text-sm">Key<input value={form.data.key} onChange={e=>form.setData('key',e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/30 px-3 outline-none focus:border-cyan-300/40"/></label><label className="block text-sm">Locale<input value={form.data.locale} onChange={e=>form.setData('locale',e.target.value)} maxLength={8} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/30 px-3"/></label><label className="block text-sm">Title<input value={form.data.title} onChange={e=>form.setData('title',e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/30 px-3"/></label><label className="block text-sm">Body<textarea value={form.data.body} onChange={e=>form.setData('body',e.target.value)} rows={8} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3"/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.data.is_published} onChange={e=>form.setData('is_published',e.target.checked)}/> Published</label><button disabled={form.processing} className="flex min-h-11 items-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/10 px-4 font-semibold text-cyan-100"><Save size={16}/> Save content</button></form></NxCard><NxCard className="p-0"><div className="border-b border-white/5 px-5 py-4 text-sm font-bold text-cyan-300">Stored blocks</div><div className="divide-y divide-white/5">{blocks.length===0?<div className="px-5 py-10 text-slate-500">No content blocks yet.</div>:blocks.map(block=><button type="button" key={`${block.key}:${block.locale}`} onClick={()=>form.setData({key:block.key,locale:block.locale,title:block.title ?? '',body:block.body ?? '',is_published:block.is_published})} className="block w-full px-5 py-4 text-left hover:bg-white/[0.025]"><div className="flex items-center justify-between gap-3"><span className="font-semibold">{block.key}</span><span className="text-xs text-cyan-300">{block.locale.toUpperCase()}</span></div><p className="mt-1 truncate text-sm text-slate-400">{block.title || 'Untitled'}</p><p className="mt-1 text-xs text-slate-600">{block.is_published?'Published':'Draft'}</p></button>)}</div></NxCard></div></div></main></>;
}
