import { Head, useForm } from '@inertiajs/react';
import { FileSearch, ShieldCheck } from 'lucide-react';
import { AdminNav } from '../../components/admin/admin-nav';
import { NxCard } from '../../components/ui/nx-card';

type SafeScanSettings = { max_file_mb: number; reputation_lookup_enabled: boolean; store_raw_files: boolean; privacy_mode: string };

export default function SafeScanAdmin({ settings }: { settings: SafeScanSettings }) {
  const form = useForm(settings);
  const submit = () => form.post('/secure-control/safescan', { preserveScroll: true });
  return <><Head title="SafeScan Admin" /><main className="min-h-screen bg-slate-950 px-4 py-7 text-white sm:px-8"><div className="mx-auto max-w-5xl"><AdminNav active="SafeScan" /><div className="mb-6 flex items-center gap-3"><FileSearch className="text-cyan-300"/><div><h1 className="text-3xl font-black">SafeScan Admin</h1><p className="text-sm text-slate-400">Privacy-first file analysis controls.</p></div></div><div className="grid gap-5 lg:grid-cols-2"><NxCard><label className="text-sm font-semibold">Maximum browser file size (MB)</label><input className="mt-3 min-h-11 w-full rounded-xl border border-white/10 bg-slate-900 px-3" type="number" min={1} max={512} value={form.data.max_file_mb} onChange={(e)=>form.setData('max_file_mb',Number(e.target.value))}/><label className="mt-5 flex min-h-11 items-center justify-between gap-3"><span>Optional hash reputation lookup</span><input type="checkbox" checked={form.data.reputation_lookup_enabled} onChange={(e)=>form.setData('reputation_lookup_enabled',e.target.checked)}/></label><label className="mt-3 flex min-h-11 items-center justify-between gap-3"><span>Store raw files</span><input type="checkbox" checked={form.data.store_raw_files} onChange={(e)=>form.setData('store_raw_files',e.target.checked)} disabled/></label><p className="mt-2 text-xs leading-6 text-slate-500">Raw file storage is intentionally locked OFF in the zero-storage architecture.</p><button type="button" onClick={submit} disabled={form.processing} className="mt-6 min-h-11 rounded-xl border border-cyan-300/20 bg-cyan-300/10 px-4 font-semibold text-cyan-100 disabled:opacity-50">Save SafeScan settings</button></NxCard><NxCard><div className="flex items-center gap-2 text-emerald-300"><ShieldCheck size={19}/><strong>Privacy Guard</strong></div><div className="mt-5 space-y-3 text-sm">{[['Browser-side analysis','ON'],['Raw file upload','OFF'],['Zero-storage mode',form.data.privacy_mode],['Hash-only reputation',form.data.reputation_lookup_enabled?'ON':'OFF']].map(([label,value])=><div key={label} className="flex items-center justify-between rounded-xl border border-white/5 bg-black/20 px-4 py-3"><span>{label}</span><strong>{value}</strong></div>)}</div></NxCard></div></div></main></>;
}
